import type {
  Exercise,
  OnboardingOption,
  OnboardingQuestion,
  OnboardingQuestionKey,
} from '@/lib/types';

export interface WorkingExercise extends Exercise {
  isMultiDay?: boolean;
}

export const WORKING_EXERCISES: WorkingExercise[] = [
  {
    id: 1,
    titre: 'Cercles de contrôle',
    titre_en: 'Circles of Control',
    description_courte: 'Distinguer ce qui dépend de soi pour apaiser l’anxiété et reprendre la main.',
    duree_moyenne: '5-10 min',
    effort_cognitif: 'Modéré',
    color: '#EDE9FE', // violet pastel
    symptomes: ['Anxiété', 'Stress', 'Perte de contrôle'],
  },
  {
    id: 2,
    titre: 'Respiration diaphragmatique',
    titre_en: 'Diaphragmatic Breathing',
    description_courte: 'Ralentir le rythme cardiaque et réguler le système nerveux par le souffle.',
    duree_moyenne: '3-5 min',
    effort_cognitif: 'Faible',
    color: '#E0F2FE', // bleu ciel pastel
    symptomes: ['Stress aigu', 'Tensions physiques', 'Panique'],
  },
  {
    id: 3,
    titre: 'Restructuration cognitive',
    titre_en: 'Cognitive Restructuring',
    description_courte: 'Identifier et assouplir les pensées automatiques pour sortir des ruminations.',
    duree_moyenne: '10-15 min',
    effort_cognitif: 'Intense',
    color: '#FEF3C7', // ambre pastel
    symptomes: ['Ruminations', 'Idées noires', 'Doute'],
  },
  {
    id: 4,
    titre: 'Activation comportementale',
    titre_en: 'Behavioral Activation',
    description_courte: 'Reprendre progressivement des activités ressourçantes étape par étape.',
    duree_moyenne: 'Plusieurs jours',
    effort_cognitif: 'Modéré',
    color: '#DCFCE7', // vert pastel
    symptomes: ['Baisse d’énergie', 'Perte de motivation', 'Isolement'],
    isMultiDay: true,
  },
];

export const ONBOARDING_QUESTIONS_FALLBACK: OnboardingQuestion[] = [
  { key: 'q1_goals', display_order: 1, max_choices: 3 },
  { key: 'q2_impact', display_order: 2, max_choices: 1 },
  { key: 'q3_moments', display_order: 3, max_choices: 3 },
  { key: 'q4_experience', display_order: 4, max_choices: 1 },
  { key: 'q5_tone', display_order: 5, max_choices: 1 },
];

export const ONBOARDING_OPTIONS_FALLBACK: OnboardingOption[] = [
  // Q1 Goals (max 3 choices, suggestable except 'unsure')
  {
    question_key: 'q1_goals',
    option_key: 'stress',
    label_fr: 'Mieux gérer mon stress',
    label_en: 'Better manage my stress',
    display_order: 1,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q1_goals',
    option_key: 'worries',
    label_fr: 'Apaiser mes inquiétudes',
    label_en: 'Ease my worries',
    display_order: 2,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q1_goals',
    option_key: 'emotions',
    label_fr: 'Mieux comprendre mes émotions',
    label_en: 'Better understand my emotions',
    display_order: 3,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q1_goals',
    option_key: 'motivation',
    label_fr: 'Retrouver de la motivation',
    label_en: 'Regain motivation',
    display_order: 4,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q1_goals',
    option_key: 'confidence',
    label_fr: 'Prendre confiance en moi',
    label_en: 'Build self-confidence',
    display_order: 5,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q1_goals',
    option_key: 'relationships',
    label_fr: 'Mieux vivre mes relations',
    label_en: 'Improve my relationships',
    display_order: 6,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q1_goals',
    option_key: 'sleep',
    label_fr: 'Améliorer mon sommeil',
    label_en: 'Improve my sleep',
    display_order: 7,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q1_goals',
    option_key: 'self_care',
    label_fr: 'Prendre du temps pour moi',
    label_en: 'Take time for myself',
    display_order: 8,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q1_goals',
    option_key: 'unsure',
    label_fr: 'Je ne sais pas encore',
    label_en: 'I do not know yet',
    display_order: 9,
    is_exclusive: true,
    suggestable: false, // Patient escape hatch: not suggestable by psy
  },

  // Q2 Impact (max 1 choice)
  {
    question_key: 'q2_impact',
    option_key: 'rarely',
    label_fr: 'Très peu, ça me gêne rarement',
    label_en: 'Very little, it rarely bothers me',
    display_order: 1,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q2_impact',
    option_key: 'sometimes',
    label_fr: 'Un peu, ça me gêne par moments',
    label_en: 'A little, it bothers me at times',
    display_order: 2,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q2_impact',
    option_key: 'moderate',
    label_fr: 'Assez, ça complique certaines journées',
    label_en: 'Quite a bit, it complicates some days',
    display_order: 3,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q2_impact',
    option_key: 'often',
    label_fr: 'Beaucoup, ça rend souvent mon quotidien difficile',
    label_en: 'A lot, it often makes daily life hard',
    display_order: 4,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q2_impact',
    option_key: 'overwhelming',
    label_fr: 'Énormément, ça prend presque toute la place',
    label_en: 'Enormously, it takes up almost all the space',
    display_order: 5,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q2_impact',
    option_key: 'unsure',
    label_fr: 'J’ai du mal à l’évaluer',
    label_en: 'I find it hard to evaluate',
    display_order: 6,
    is_exclusive: false,
    suggestable: false,
  },

  // Q3 Moments (max 3 choices)
  {
    question_key: 'q3_moments',
    option_key: 'morning',
    label_fr: 'Au réveil',
    label_en: 'Upon waking up',
    display_order: 1,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q3_moments',
    option_key: 'work_studies',
    label_fr: 'Au travail ou pendant mes études',
    label_en: 'At work or during my studies',
    display_order: 2,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q3_moments',
    option_key: 'solitude',
    label_fr: 'Dans les moments de solitude',
    label_en: 'In moments of solitude',
    display_order: 3,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q3_moments',
    option_key: 'social',
    label_fr: 'Dans mes échanges avec les autres',
    label_en: 'In interactions with others',
    display_order: 4,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q3_moments',
    option_key: 'evening',
    label_fr: 'En fin de journée',
    label_en: 'At the end of the day',
    display_order: 5,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q3_moments',
    option_key: 'bedtime',
    label_fr: 'Au moment de me coucher',
    label_en: 'At bedtime',
    display_order: 6,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q3_moments',
    option_key: 'night',
    label_fr: 'Pendant la nuit',
    label_en: 'During the night',
    display_order: 7,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q3_moments',
    option_key: 'none',
    label_fr: 'Je n’ai pas repéré de moment précis',
    label_en: 'I haven’t noticed a specific moment',
    display_order: 8,
    is_exclusive: true,
    suggestable: false,
  },

  // Q4 Experience (max 1 choice)
  {
    question_key: 'q4_experience',
    option_key: 'never',
    label_fr: 'Je n’en ai jamais fait',
    label_en: 'I have never done any',
    display_order: 1,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q4_experience',
    option_key: 'tried',
    label_fr: 'J’en ai déjà essayé, sans en faire régulièrement',
    label_en: 'I have tried, without doing it regularly',
    display_order: 2,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q4_experience',
    option_key: 'used_to',
    label_fr: 'J’en faisais régulièrement, mais plus aujourd’hui',
    label_en: 'I used to do them regularly, but not anymore',
    display_order: 3,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q4_experience',
    option_key: 'regular',
    label_fr: 'J’en fais déjà régulièrement',
    label_en: 'I already do them regularly',
    display_order: 4,
    is_exclusive: false,
    suggestable: true,
  },

  // Q5 Tone (max 1 choice)
  {
    question_key: 'q5_tone',
    option_key: 'gentle',
    label_fr: 'Avec douceur et des mots rassurants',
    label_en: 'With gentleness and reassuring words',
    display_order: 1,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q5_tone',
    option_key: 'direct',
    label_fr: 'De façon simple et directe',
    label_en: 'Simple and direct',
    display_order: 2,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q5_tone',
    option_key: 'energetic',
    label_fr: 'Avec de l’énergie et des encouragements',
    label_en: 'With energy and encouragement',
    display_order: 3,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q5_tone',
    option_key: 'calm_precise',
    label_fr: 'De façon posée, avec des explications précises',
    label_en: 'Calmly, with precise explanations',
    display_order: 4,
    is_exclusive: false,
    suggestable: true,
  },
  {
    question_key: 'q5_tone',
    option_key: 'none',
    label_fr: 'Je n’ai pas de préférence',
    label_en: 'I have no preference',
    display_order: 5,
    is_exclusive: false,
    suggestable: false,
  },
];
