-- ============================================================================
-- Migration 0001 — Portail Psy UMi (v0)
-- Compte praticien · invitations/sièges (code par patient) · rattachement
-- psy<->patient (patient maître : bascule/retrait) · accès conditionné au
-- siège actif · traçage "exercice fait/non fait" · audit.
--
-- Appliquer via : Supabase Studio > SQL Editor  ou  `supabase db push`.
-- Rollback : voir la fin du fichier.
-- Prérequis : table publique `exercises` (id bigint). Extension pgcrypto (Supabase: activée).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. Utilitaires
-- ----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end;
$$;

-- Génération d'un code lisible : UMI-XXXX-XX (alphabet sans 0/O/1/I/L)
create or replace function public.gen_invite_code()
returns text language plpgsql as $$
declare
  alphabet constant text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  n        constant int  := length('ABCDEFGHJKMNPQRSTUVWXYZ23456789');
  s text := '';
  i int;
begin
  for i in 1..6 loop
    s := s || substr(alphabet, 1 + floor(random() * n)::int, 1);
  end loop;
  return 'UMI-' || substr(s,1,4) || '-' || substr(s,5,2);
end;
$$;
-- Interne : ne pas exposer via l'API.
revoke all on function public.gen_invite_code() from public, anon, authenticated;

-- ----------------------------------------------------------------------------
-- 1. PRACTITIONERS (compte psy — minimal)
-- ----------------------------------------------------------------------------
create table if not exists public.practitioners (
  id                  uuid primary key references auth.users (id) on delete cascade,
  practitioner_number bigint generated by default as identity unique,   -- psy 1, 2, 3… (auto)
  first_name          text,
  last_name           text,
  locale              text not null default 'fr' check (locale in ('fr','en')),  -- langue portail
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

drop trigger if exists practitioners_set_updated_at on public.practitioners;
create trigger practitioners_set_updated_at
  before update on public.practitioners
  for each row execute function public.set_updated_at();

alter table public.practitioners enable row level security;

drop policy if exists practitioner_select_own on public.practitioners;
create policy practitioner_select_own on public.practitioners
  for select using (id = auth.uid());
drop policy if exists practitioner_insert_self on public.practitioners;
create policy practitioner_insert_self on public.practitioners
  for insert with check (id = auth.uid());
drop policy if exists practitioner_update_own on public.practitioners;
create policy practitioner_update_own on public.practitioners
  for update using (id = auth.uid()) with check (id = auth.uid());

-- ----------------------------------------------------------------------------
-- 2. PATIENT_SEATS (invitation + rattachement + futur siège de facturation)
-- ----------------------------------------------------------------------------
create table if not exists public.patient_seats (
  id               uuid primary key default gen_random_uuid(),
  practitioner_id  uuid not null references public.practitioners (id) on delete cascade,
  patient_user_id  uuid references auth.users (id) on delete set null,
  label            text,
  invite_code      text not null unique,
  invite_email     text,
  status           text not null default 'invited'
                     check (status in ('invited','active','paused','revoked','released','expired')),
  created_at       timestamptz not null default now(),
  expires_at       timestamptz not null default (now() + interval '30 days'),
  redeemed_at      timestamptz,
  revoked_at       timestamptz,
  released_at      timestamptz
);

create index if not exists patient_seats_practitioner_idx on public.patient_seats (practitioner_id);
create index if not exists patient_seats_patient_idx      on public.patient_seats (patient_user_id);
-- Un seul siège actif par patient (garantit RG-10 au niveau data).
create unique index if not exists patient_seats_one_active_per_patient
  on public.patient_seats (patient_user_id) where status = 'active';

alter table public.patient_seats enable row level security;

-- Le psy gère uniquement ses propres sièges.
drop policy if exists seat_practitioner_all on public.patient_seats;
create policy seat_practitioner_all on public.patient_seats
  for all using (practitioner_id = auth.uid())
  with check (practitioner_id = auth.uid());
-- Le patient lit le siège auquel il est rattaché.
drop policy if exists seat_patient_select on public.patient_seats;
create policy seat_patient_select on public.patient_seats
  for select using (patient_user_id = auth.uid());

-- ----------------------------------------------------------------------------
-- 3. EXERCISE_COMPLETIONS ("fait/non fait" — métadonnée, sans contenu)
-- ----------------------------------------------------------------------------
create table if not exists public.exercise_completions (
  id               uuid primary key default gen_random_uuid(),
  patient_user_id  uuid not null references auth.users (id) on delete cascade,
  exercise_id      bigint not null references public.exercises (id),
  completed_at     timestamptz not null default now()
);
create index if not exists exercise_completions_patient_idx
  on public.exercise_completions (patient_user_id, completed_at);

alter table public.exercise_completions enable row level security;

-- Le patient n'enregistre une complétion que s'il a un siège actif (RG-6).
drop policy if exists completion_patient_insert on public.exercise_completions;
create policy completion_patient_insert on public.exercise_completions
  for insert with check (
    patient_user_id = auth.uid()
    and exists (
      select 1 from public.patient_seats s
      where s.patient_user_id = auth.uid() and s.status = 'active'
    )
  );
-- Le patient lit les siennes.
drop policy if exists completion_patient_select on public.exercise_completions;
create policy completion_patient_select on public.exercise_completions
  for select using (patient_user_id = auth.uid());
-- Le psy lit celles d'un patient rattaché ACTIF, sur la PÉRIODE de rattachement (RG-14).
drop policy if exists completion_practitioner_select on public.exercise_completions;
create policy completion_practitioner_select on public.exercise_completions
  for select using (
    exists (
      select 1 from public.patient_seats s
      where s.patient_user_id = exercise_completions.patient_user_id
        and s.practitioner_id = auth.uid()
        and s.status = 'active'
        and exercise_completions.completed_at >= s.redeemed_at
    )
  );

-- ----------------------------------------------------------------------------
-- 4. AUDIT_EVENTS (traçabilité des actions sensibles) — accès via fonctions only
-- ----------------------------------------------------------------------------
create table if not exists public.audit_events (
  id             uuid primary key default gen_random_uuid(),
  actor_user_id  uuid,
  action         text not null,
  target_seat_id uuid,
  created_at     timestamptz not null default now()
);
alter table public.audit_events enable row level security;
-- Aucune policy => aucun accès direct (les fonctions security definer y écrivent).

-- ----------------------------------------------------------------------------
-- 5. FONCTIONS MÉTIER (RPC)
-- ----------------------------------------------------------------------------

-- 5.1 create_invitation (psy) : crée un siège 'invited' avec un code unique.
create or replace function public.create_invitation(
  p_label text default null,
  p_invite_email text default null
) returns public.patient_seats
language plpgsql security definer set search_path = public as $$
declare v_seat public.patient_seats; v_code text; v_try int := 0;
begin
  if not exists (select 1 from public.practitioners where id = auth.uid()) then
    raise exception 'not_practitioner';
  end if;
  loop
    v_try := v_try + 1;
    v_code := public.gen_invite_code();
    begin
      insert into public.patient_seats (practitioner_id, label, invite_email, invite_code)
      values (auth.uid(), p_label, p_invite_email, v_code)
      returning * into v_seat;
      exit;
    exception when unique_violation then
      if v_try >= 10 then raise exception 'code_generation_failed'; end if;
    end;
  end loop;
  insert into public.audit_events(actor_user_id, action, target_seat_id)
    values (auth.uid(), 'invitation_created', v_seat.id);
  return v_seat;
end; $$;

-- 5.2 regenerate_code (psy) : nouveau code pour un siège 'invited' lui appartenant.
create or replace function public.regenerate_code(p_seat_id uuid)
returns public.patient_seats
language plpgsql security definer set search_path = public as $$
declare v_seat public.patient_seats; v_code text; v_try int := 0;
begin
  select * into v_seat from public.patient_seats
    where id = p_seat_id and practitioner_id = auth.uid() for update;
  if not found then raise exception 'not_owner'; end if;
  if v_seat.status <> 'invited' then raise exception 'seat_not_invited'; end if;
  loop
    v_try := v_try + 1; v_code := public.gen_invite_code();
    begin
      update public.patient_seats
        set invite_code = v_code, expires_at = now() + interval '30 days'
        where id = p_seat_id returning * into v_seat;
      exit;
    exception when unique_violation then
      if v_try >= 10 then raise exception 'code_generation_failed'; end if;
    end;
  end loop;
  insert into public.audit_events(actor_user_id, action, target_seat_id)
    values (auth.uid(), 'code_regenerated', p_seat_id);
  return v_seat;
end; $$;

-- 5.3 revoke_seat (psy) : met fin à un siège 'active' ou annule un 'invited'.
create or replace function public.revoke_seat(p_seat_id uuid)
returns public.patient_seats
language plpgsql security definer set search_path = public as $$
declare v_seat public.patient_seats;
begin
  select * into v_seat from public.patient_seats
    where id = p_seat_id and practitioner_id = auth.uid() for update;
  if not found then raise exception 'not_owner'; end if;
  if v_seat.status not in ('active','invited') then
    raise exception 'seat_not_active_or_invited';
  end if;
  update public.patient_seats set status = 'revoked', revoked_at = now()
    where id = p_seat_id returning * into v_seat;
  insert into public.audit_events(actor_user_id, action, target_seat_id)
    values (auth.uid(), 'seat_revoked', p_seat_id);
  return v_seat;
end; $$;

-- 5.4 redeem_seat_code (patient) : rattache ; bascule auto si déjà rattaché (RG-7).
create or replace function public.redeem_seat_code(p_code text)
returns public.patient_seats
language plpgsql security definer set search_path = public as $$
declare v_seat public.patient_seats;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;

  select * into v_seat from public.patient_seats
    where upper(invite_code) = upper(p_code) for update;
  if not found then raise exception 'invalid_code'; end if;
  if v_seat.status <> 'invited' then raise exception 'code_already_used'; end if;
  if v_seat.expires_at < now() then
    update public.patient_seats set status = 'expired' where id = v_seat.id;
    raise exception 'code_expired';
  end if;

  -- Bascule : libère le siège actif courant du patient, s'il existe.
  update public.patient_seats
    set status = 'released', released_at = now()
    where patient_user_id = auth.uid() and status = 'active';

  update public.patient_seats
    set patient_user_id = auth.uid(), status = 'active', redeemed_at = now()
    where id = v_seat.id returning * into v_seat;

  insert into public.audit_events(actor_user_id, action, target_seat_id)
    values (auth.uid(), 'code_redeemed', v_seat.id);
  return v_seat;
end; $$;

-- 5.5 release_my_seat (patient) : se délie (RG-8).
create or replace function public.release_my_seat()
returns public.patient_seats
language plpgsql security definer set search_path = public as $$
declare v_seat public.patient_seats;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  update public.patient_seats set status = 'released', released_at = now()
    where patient_user_id = auth.uid() and status = 'active'
    returning * into v_seat;
  if not found then raise exception 'no_active_seat'; end if;
  insert into public.audit_events(actor_user_id, action, target_seat_id)
    values (auth.uid(), 'seat_released', v_seat.id);
  return v_seat;
end; $$;

-- 5.6 record_completion (patient) : enregistre "fait" si rattaché actif (RG-6/11).
create or replace function public.record_completion(p_exercise_id bigint)
returns public.exercise_completions
language plpgsql security definer set search_path = public as $$
declare v_row public.exercise_completions;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if not exists (
    select 1 from public.patient_seats where patient_user_id = auth.uid() and status = 'active'
  ) then raise exception 'no_active_seat'; end if;
  insert into public.exercise_completions(patient_user_id, exercise_id)
    values (auth.uid(), p_exercise_id) returning * into v_row;
  return v_row;
end; $$;

-- Droits d'exécution
revoke all on function public.create_invitation(text, text)   from public, anon;
revoke all on function public.regenerate_code(uuid)            from public, anon;
revoke all on function public.revoke_seat(uuid)                from public, anon;
revoke all on function public.redeem_seat_code(text)           from public, anon;
revoke all on function public.release_my_seat()                from public, anon;
revoke all on function public.record_completion(bigint)        from public, anon;
grant execute on function public.create_invitation(text, text) to authenticated;
grant execute on function public.regenerate_code(uuid)         to authenticated;
grant execute on function public.revoke_seat(uuid)             to authenticated;
grant execute on function public.redeem_seat_code(text)        to authenticated;
grant execute on function public.release_my_seat()             to authenticated;
grant execute on function public.record_completion(bigint)     to authenticated;

-- NOTE anti-abus (RG/§14.3) : ajouter un rate-limit sur redeem_seat_code
-- (ex. via Edge Function / politique côté API) — non géré au niveau SQL seul.

-- ============================================================================
-- ROLLBACK (exécuter manuellement pour annuler cette migration)
-- ----------------------------------------------------------------------------
-- drop function if exists public.record_completion(bigint);
-- drop function if exists public.release_my_seat();
-- drop function if exists public.redeem_seat_code(text);
-- drop function if exists public.revoke_seat(uuid);
-- drop function if exists public.regenerate_code(uuid);
-- drop function if exists public.create_invitation(text, text);
-- drop table if exists public.audit_events;
-- drop table if exists public.exercise_completions;
-- drop table if exists public.patient_seats;
-- drop table if exists public.practitioners;
-- drop function if exists public.gen_invite_code();
-- drop function if exists public.set_updated_at();
-- ============================================================================
